name: "[CIP] Create release"

on:
  workflow_dispatch:
  push:
    branches:
      - production

jobs:
  create-tag-release:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'push' || github.event_name == 'workflow_dispatch') &&
      github.ref_name == 'production'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install NPM dependencies and create tag release
        run: |
          npm install
          npx semantic-release -d
        env:
          GITHUB_TOKEN: ${{ secrets.DEVIOPS_PAT }}